# Generated by Django 5.0.3 on 2024-08-27 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klic_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='klic_course')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('AC', 'Accounting Careers'), ('BOC', 'Back Office Careers'), ('DC', 'Designing Careers'), ('DAC', 'Digital Arts Careers'), ('DF', 'Digital Freelancing'), ('FOC', 'Front Office Careers'), ('IHANC', 'IT Hardware and Networking Careers'), ('MNCJ', 'Management New Collar Jobs'), ('PC', 'Programming Careers')], max_length=5)),
            ],
        ),
    ]
