# Generated by Django 5.0.3 on 2024-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuracomputer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klic_course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='klic_course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='klic_course',
            name='image',
            field=models.ImageField(upload_to='kliccourse'),
        ),
    ]
