# Generated by Django 5.0.7 on 2024-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuracomputer', '0002_klic_course_description_klic_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klic_course',
            name='type',
            field=models.CharField(choices=[('AC', 'Accounting Careers'), ('BOC', 'Back Office Careers'), ('DC', 'Designing Careers'), ('DAC', 'Digital Arts Careers'), ('DF', 'Digital Freelancing'), ('FOC', 'Front Office Careers'), ('IHANC', 'IT Hardware and Networking Careers'), ('M', 'Management'), ('NCJ', 'New Collar Jobs'), ('PC', 'Programming Careers')], max_length=5),
        ),
    ]
